name: CI

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
  cypress-run:
    name: e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - run: node -v
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start 3000
          wait-on: 'http://localhost:3000'
